name: Build Release

on:
  push:
    tags:
      - 'pmd_releases/*'
      - '!pmd_releases/*-SNAPSHOT'
  workflow_dispatch:

jobs:
  build:
    name: Build Release
    uses: ./.github/workflows/build.yml
